### PR TITLE
Tidied Up

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-c84f8c?style=for-the-badge&logoColor=white&logo=RuboCop
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Changes]

- Replaced badge with modern version

- Tidied up links

- Sorted schematic into `/Resources/`

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/SmartWatch

### CODE REVIEW

**Comment by yunkai1841** [comment]
I dont know which license is better. Do you think apache2.0 is appropriate? There are so many choice on github.

**Comment by ElectronicsArchiver** [comment]
Well I usually go with **AGPLv3** since its a strong 
copyleft license and retains the same license opposed
to for example Apache 2.

Not sure if you checked the overview
at https://choosealicense.com/licenses/

**Comment by ElectronicsArchiver** [comment]
Btw, as you might know, changing a license 
can only be done if all contributors that 
have active code in a repo agree.

*And with that I will state that I'm*
*fine with you changing it ( currently ).*

*Not that repos usually change it anyways~*

**Comment by yunkai1841** [comment]
I got it. I will not change the license. 
Yes, I checked the choosealicense, but every license looks the same to me.
Anyway, thanks to teaching me!

**Comment by ElectronicsArchiver** [comment]
Just so you are aware, with Apache 2 you
allow others to use a different license.

> A permissive license whose main conditions require preservation of copyright and license notices. Contributors provide an express grant of patent rights. Licensed works, modifications, and larger works may be distributed under different terms and without source code.

**Comment by yunkai1841** [comment]
If the license is Apache 2, others should use the same one right?
If you recommend, I can change the license.

**Comment by ElectronicsArchiver** [comment]
Sorry for the late response, the notification didn't show up :c

Apache 2 demands that your license notice is kept in derivative works.
However, ` Licensed works, modifications, and larger works ` can be
distrubuted with a different license.

So if you are concerened about it, you'd best choose another license.

**Comment by ElectronicsArchiver** [comment]
AGPLv3 & GPLv3 for example require that the same license is used in derivative works.

**Comment by yunkai1841** [comment]
Its ok. The license will be not changed. 
Anyway, thanks.

**Pull request merged**
